### ISSUE TITLE
Revisión de la base de datos

### ISSUE THREAD

**Issue by maikol-solis** [JEIKEL195/Bitacora-Grupo-5-CA-0204-II-2024-#1]
Hola. 

Según lo que conversamos el jueves, creo que deben revisar si deben continuar con esa base de datos o no. Esto ya que me parece que los valores son muy uniformes entre categorías, haciéndome sospechar que se trata de datos generados. 

Por favor, revisen esto antes de seguir con la bitácora #3. 

Muchas gracias.

**Comment by Jeikel-Navarro** [comment]
Buenas noches, espero se encuentre bien. Estuvimos averiguando más acerca de la base de datos, y aunque estaba respaldada por la MIT nos dimos cuenta que eran datos generados con un propósito didáctico, de manera que decidimos descartar esta base de datos y hemos estado buscando bases con mantengan cierta relación con lo que llevamos, ya que el tema nos sigue pareciendo muy interesante y de gran provecho para lo que es la carrera. Por tanto, agradecemos su observación ya que nos ayuda a obtener un análisis más basado en la realidad lo cual es el fin de nuestro proyecto. Muchas gracias.El 7 oct 2024 4:39 a. m., Maikol Solís ***@***.***> escribió:
Hola.
Según lo que conversamos el jueves, creo que deben revisar si deben continuar con esa base de datos o no. Esto ya que me parece que los valores son muy uniformes entre categorías, haciéndome sospechar que se trata de datos generados.
Por favor, revisen esto antes de seguir con la bitácora #3.
Muchas gracias.

**Comment by maikol-solis** [comment]
Con mucho gusto. 

Cualquier problema que encuentren con la nueva base de datos me avisan. 

Saludos.
